#!/usr/bin/env python3
"""Render one Markdown file from another repository into a JS data module.

The site never hand-copies documents it does not own (see WEBMASTER.md): the
Charter lives in the handbook repo and the Phantom status beside Phantom's
code. This reads the file as *committed* at --ref, so the page always matches a
real, reviewable commit, and records that commit in the output.
"""
import argparse, json, pathlib, subprocess, sys
import markdown

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", required=True)
    ap.add_argument("--file", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--export", required=True)
    ap.add_argument("--source", required=True)
    ap.add_argument("--ref", default="HEAD")
    a = ap.parse_args()

    def git(*args):
        return subprocess.run(["git", "-C", a.repo, *args], capture_output=True, text=True)

    sha = git("rev-parse", a.ref)
    if sha.returncode != 0:
        print(f"FAIL: cannot resolve {a.ref} in {a.repo}", file=sys.stderr); return 1
    sha = sha.stdout.strip()
    text = git("show", f"{sha}:{a.file}")
    if text.returncode != 0:
        print(f"FAIL: {a.file} not found at {sha}", file=sys.stderr); return 1

    html = markdown.markdown(text.stdout, extensions=["tables", "toc"],
                             extension_configs={"toc": {"permalink": False}})
    data = {"html": html, "source": a.source, "commit": sha}
    pathlib.Path(a.out).write_text(
        "// GENERATED by scripts/build-markdown-page.py — do not hand-edit.\n"
        f"// Source: {a.source} at {sha}\n"
        f"export const {a.export} = {json.dumps(data, ensure_ascii=False)};\n")
    return 0

if __name__ == "__main__":
    sys.exit(main())
