#!/usr/bin/env bash
# Refresh the self-hosted web fonts under frontend/public/fonts.
#
# tnhc.dev serves its own fonts. It used to link api.fontshare.com and
# fonts.googleapis.com, so every visitor's browser contacted two third parties
# before the first paint — and one of those requests (Cabinet Grotesk, five
# weights) was for a font no stylesheet in the project referenced.
#
# Run this only when a weight is added or a font is updated. The output is
# committed; the site must never fetch a font at runtime.
set -euo pipefail
cd "$(dirname "$0")/../frontend/public/fonts"

UA='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36'

# ── Figtree (SIL OFL 1.1) — the TNHC typeface ────────────────────────────────
# From the official repository, pinned, so a refresh is reproducible.
echo "Figtree…"
FIG=https://raw.githubusercontent.com/erikdkennedy/figtree/032dfa7fe219ef3a02890d6d3add84eacc9aebfe
{
  echo "/* Figtree — self-hosted. SIL OFL 1.1; see LICENSE-Figtree.txt."
  echo "   Generated by scripts/vendor-fonts.sh — do not hand-edit. */"
  for pair in 400:Regular 500:Medium 700:Bold 900:Black; do
    w=${pair%%:*}; n=${pair##*:}
    curl -sfL "$FIG/fonts/webfonts/Figtree-$n.woff2" -o "figtree-$w.woff2"
    printf "@font-face {\n  font-family: 'Figtree';\n  src: url('/fonts/figtree-%s.woff2') format('woff2');\n  font-weight: %s;\n  font-style: normal;\n  font-display: swap;\n}\n" "$w" "$w"
  done
} > figtree.css
curl -sfL "$FIG/OFL.txt" -o LICENSE-Figtree.txt

# ── JetBrains Mono (OFL) — the federation diagram's labels ───────────────────
echo "JetBrains Mono…"
{
  echo "/* JetBrains Mono — self-hosted. SIL OFL 1.1; see LICENSE-JetBrainsMono.txt."
  echo "   Generated by scripts/vendor-fonts.sh — do not hand-edit. */"
  python3 - <<'PY'
import re, io, urllib.request
req = urllib.request.Request(
    "https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;700&display=swap",
    headers={"User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/120 Safari/537.36"})
css = urllib.request.urlopen(req).read().decode()
seen = set()
for block in re.findall(r'@font-face \{(.*?)\}', css, re.S):
    w = re.search(r'font-weight: (\d+)', block)
    u = re.search(r'src: url\((https://[^)]+\.woff2)\)', block)
    rng = re.search(r'unicode-range: ([^;]+);', block)
    if not (w and u):
        continue
    # latin subset only; the diagram renders node names and numbers
    if rng and 'U+0000-00FF' not in rng.group(1):
        continue
    if w.group(1) in seen:
        continue
    seen.add(w.group(1))
    name = f'jetbrains-mono-{w.group(1)}.woff2'
    urllib.request.urlretrieve(u.group(1), name)
    print(f"@font-face {{\n  font-family: 'JetBrains Mono';\n  src: url('/fonts/{name}') format('woff2');\n"
          f"  font-weight: {w.group(1)};\n  font-style: normal;\n  font-display: swap;\n}}")
PY
} > jetbrains-mono.css

curl -sfL "https://raw.githubusercontent.com/JetBrains/JetBrainsMono/master/OFL.txt" -o LICENSE-JetBrainsMono.txt

echo "Done. $(ls *.woff2 | wc -l) faces, $(du -sh . | cut -f1) total."
echo "Verify nothing external remains:  grep -rn 'fontshare\|googleapis' ../index.html"
